[user]
name = "Ken Banks"
email = "kenbanks.peng@gmail.com"

[colors]
"commit_id" = { fg = "yellow", bold = false }
"change_id" = { fg = "yellow", bold = false }
"prefix" = { bold = false }
"rest" = "#707070"
"divergent rest" = "yellow"
"divergent prefix" = { fg = "yellow", underline = true }
